### ISSUE TITLE
Uploading and Pavering Shapefiles

### ISSUE THREAD

**Issue by fabian-eae** [energyaccessexplorer/paver#8]

**Comment by fabian-eae** [comment]
Closing this. Open a new issue/bug-report.

**Comment by Santi-eae** [comment]
Opening this up @fabian-eae although the backend recognizes and allows you to upload shapefiles paver does not process this format. This is for any geography. A screenshot testing it in Tanzania with powerplants 
![image](https://github.com/energyaccessexplorer/paver/assets/77996538/a7a72aff-0832-4b91-b63f-e2edddbd5e3c)
